import { AdsIcon, BankAccountIcon, VideoGuideIcon } from '../constants/svgs';
import {
  ChatIcon,
  HelpIcon,
  NavChartIcon,
  NavDeliveryIcon,
  NavHomeIcon,
  CustomIcon,
  NavMenuIcon,
  NavProductIcon,
  NavProfileIcon,
  NavSupportIcon,
  NavTagIcon,
  RewardIcon,
  ShoppingCartIcon,
} from '../constants';

// import NavAddIcon from '../public/assets/images/add-icon.svg';

export const VENDOR_DASHBOARD_LINKS = [
  {
    TITLE: 'Users',
    // LINK: '/vendor/[vendorId]',
    LINK: '/users',
    SLUG: 'users',
    PROTECTED: true,
    // ISBUSINESS: true,
    ISCUSTOMER: true,
    ICON: (isActive: boolean) => <CustomIcon isActive={isActive} />,
  },
  {
    TITLE: 'Guarantors',
    LINK: '/guarantors',
    SLUG: 'guarantors',
    PROTECTED: true,
    // ISBUSINESS: true,
    ISCUSTOMER: true,
    ICON: (isActive: boolean) => <CustomIcon isActive={isActive} />,
  },
  {
    TITLE: 'Loans',
    LINK: '/loans',
    SLUG: 'loans',
    PROTECTED: true,
    // ISBUSINESS: true,
    ISCUSTOMER: true,
    ICON: (isActive: boolean) => <CustomIcon isActive={isActive} />,
  },
  {
    TITLE: 'Decision Models',
    LINK: '/decision-models',
    SLUG: 'decision-models',
    PROTECTED: true,
    // ISBUSINESS: true,
    ISCUSTOMER: true,
    ICON: (isActive: boolean) => <CustomIcon isActive={isActive} />,
  },
  {
    TITLE: 'Savings',
    LINK: '/savings',
    SLUG: 'savings',
    PROTECTED: true,
    // ISBUSINESS: true,
    ISCUSTOMER: true,
    ICON: (isActive: boolean) => <CustomIcon isActive={isActive} />,
  },
  {
    TITLE: 'Loan Requests',
    LINK: '/loan-requests',
    SLUG: 'loan-requests',
    PROTECTED: true,
    // ISBUSINESS: true,
    ISCUSTOMER: true,
    ICON: (isActive: boolean) => <CustomIcon isActive={isActive} />,
  },
  {
    TITLE: 'Whitelist',
    LINK: '/whitelist',
    SLUG: 'whitelist',
    PROTECTED: true,
    // ISBUSINESS: true,
    ISCUSTOMER: true,
    ICON: (isActive: boolean) => <CustomIcon isActive={isActive} />,
  },
  {
    TITLE: 'Karma',
    LINK: '/karma',
    SLUG: 'karma',
    ISBUSINESS: true,
    // PROTECTED: true,
    ISCUSTOMER: true,
    ICON: (isActive: boolean) => <CustomIcon isActive={isActive} />,
  },
  {
    TITLE: 'Organization',
    LINK: '/vendor/[vendorId]/delivery-fee',
    SLUG: 'organization',
    ISBUSINESS: true,
    PROTECTED: true,
    ICON: (isActive: boolean) => <CustomIcon isActive={isActive} />,
  },
  {
    TITLE: 'Loan Products',
    LINK: '/vendor/[vendorId]/rewards',
    SLUG: 'loan-products',
    PROTECTED: true,
    ISBUSINESS: true,
    ICON: (isActive: boolean) => <CustomIcon isActive={isActive} />,
  },
  {
    TITLE: 'Savings Products',
    LINK: '/savings-products',
    SLUG: 'savings-products',
    PROTECTED: true,
    ISBUSINESS: true,
    ICON: (isActive: boolean) => <CustomIcon isActive={isActive} />,
  },
  {
    TITLE: 'Fees and Charges',
    LINK: 'fees',
    SLUG: 'fees',
    ISBUSINESS: true,
    PROTECTED: true,
    ICON: (isActive: boolean) => <CustomIcon isActive={isActive} />,
  },
  {
    TITLE: 'Transactions',
    LINK: 'transactions',
    SLUG: 'transactions',
    ISBUSINESS: false,
    PROTECTED: false,
    ICON: (isActive: boolean) => <CustomIcon isActive={isActive} />,
  },
  {
    TITLE: 'Services',
    LINK: 'services',
    SLUG: 'services',
    ISBUSINESS: false,
    PROTECTED: false,
    ICON: (isActive: boolean) => <CustomIcon isActive={isActive} />,
  },
  {
    TITLE: 'Service Account',
    LINK: 'service-account',
    SLUG: 'service-account',
    ISBUSINESS: false,
    PROTECTED: false,
    ICON: (isActive: boolean) => <CustomIcon isActive={isActive} />,
  },  {
    TITLE: 'Settlements',
    LINK: 'settlements',
    SLUG: 'settlements',
    ISBUSINESS: false,
    PROTECTED: false,
    ICON: (isActive: boolean) => <CustomIcon isActive={isActive} />,
  }, 
  {
    TITLE: 'Reports',
    LINK: 'reports',
    SLUG: 'reports',
    ISBUSINESS: false,
    PROTECTED: false,
    ICON: (isActive: boolean) => <CustomIcon isActive={isActive} />,
  },
  {
    TITLE: 'Preferences',
    LINK: 'preferences',
    SLUG: 'preferences',
    ISSETTINGS: false,
    PROTECTED: false,
    ICON: (isActive: boolean) => <CustomIcon isActive={isActive} />,
  },  {
    TITLE: 'Fees and Pricing',
    LINK: 'pricing',
    SLUG: 'pricing',
    ISSETTINGS: false,
    PROTECTED: false,
    ICON: (isActive: boolean) => <CustomIcon isActive={isActive} />,
  },  {
    TITLE: 'Audit Logs',
    LINK: 'audit-logs',
    SLUG: 'audit-logs',
    ISSETTINGS: false,
    PROTECTED: false,
    ICON: (isActive: boolean) => <CustomIcon isActive={isActive} />,
  },  
];

