import {
  HomeIcon,
  UserIcon,
  GuarantorIcon,
  LoanIcon,
  DecisionIcon,
  SavingsIcon,
  LoanRequestIcon,
  WhiteListIcon,
  KarmaIcon,
  BriefCaseIcon,
  SavingsProductIcon,
  FeesChargesIcon,
  TransactionIcon,
  ServicesIcon,
  ServiceAccountIcon,
  SettlementIcon,
  ReportIcon,
  PreferenceIcon,
  FeesPricingIcon,
  AuditIcon,
} from '../constants';

export const VENDOR_DASHBOARD_LINKS = [
  {
    TITLE: 'Dashboard',
    // LINK: '/vendor/[vendorId]',
    LINK: '/dashboard',
    SLUG: 'dashboard',
    ISDASHBOARD: true,
    ICON: (isActive: boolean) => <HomeIcon isActive={isActive} />,
  },
  {
    TITLE: 'Users',
    // LINK: '/vendor/[vendorId]',
    LINK: '/dashboard/users',
    SLUG: 'users',
    ISCUSTOMER: true,
    ICON: (isActive: boolean) => <UserIcon isActive={isActive} />,
  },
  {
    TITLE: 'Guarantors',
    LINK: '/dashboard/guarantors',
    SLUG: 'guarantors',
    ISCUSTOMER: true,
    ICON: (isActive: boolean) => <GuarantorIcon isActive={isActive} />,
  },
  {
    TITLE: 'Loans',
    LINK: '/loans',
    SLUG: 'loans',
    ISCUSTOMER: true,
    ICON: (isActive: boolean) => <LoanIcon isActive={isActive} />,
  },
  {
    TITLE: 'Decision Models',
    LINK: '/decision-models',
    SLUG: 'decision-models',
    ISCUSTOMER: true,
    ICON: (isActive: boolean) => <DecisionIcon isActive={isActive} />,
  },
  {
    TITLE: 'Savings',
    LINK: '/savings',
    SLUG: 'savings',
    ISCUSTOMER: true,
    ICON: (isActive: boolean) => <SavingsIcon isActive={isActive} />,
  },
  {
    TITLE: 'Loan Requests',
    LINK: '/loan-requests',
    SLUG: 'loan-requests',
    ISCUSTOMER: true,
    ICON: (isActive: boolean) => <LoanRequestIcon isActive={isActive} />,
  },
  {
    TITLE: 'Whitelist',
    LINK: '/whitelist',
    SLUG: 'whitelist',
    ISCUSTOMER: true,
    ICON: (isActive: boolean) => <WhiteListIcon isActive={isActive} />,
  },
  {
    TITLE: 'Karma',
    LINK: '/karma',
    SLUG: 'karma',
    ISCUSTOMER: true,
    ICON: (isActive: boolean) => <KarmaIcon isActive={isActive} />,
  },
  {
    TITLE: 'Organization',
    LINK: '/vendor/[vendorId]/delivery-fee',
    SLUG: 'organization',
    ISBUSINESS: true,
    ICON: (isActive: boolean) => <BriefCaseIcon isActive={isActive} />,
  },
  {
    TITLE: 'Loan Products',
    LINK: '/vendor/[vendorId]/rewards',
    SLUG: 'loan-products',
    ISBUSINESS: true,
    ICON: (isActive: boolean) => <LoanRequestIcon isActive={isActive} />,
  },
  {
    TITLE: 'Savings Products',
    LINK: '/savings-products',
    SLUG: 'savings-products',
    ISBUSINESS: true,
    ICON: (isActive: boolean) => <SavingsProductIcon isActive={isActive} />,
  },
  {
    TITLE: 'Fees and Charges',
    LINK: 'fees',
    SLUG: 'fees',
    ISBUSINESS: true,
    ICON: (isActive: boolean) => <FeesChargesIcon isActive={isActive} />,
  },
  {
    TITLE: 'Transactions',
    LINK: 'transactions',
    SLUG: 'transactions',
    ISBUSINESS: true,
    ICON: (isActive: boolean) => <TransactionIcon isActive={isActive} />,
  },
  {
    TITLE: 'Services',
    LINK: 'services',
    SLUG: 'services',
    ISBUSINESS: true,
    ICON: (isActive: boolean) => <ServicesIcon isActive={isActive} />,
  },
  {
    TITLE: 'Service Account',
    LINK: 'service-account',
    SLUG: 'service-account',
    ISBUSINESS: true,
    ICON: (isActive: boolean) => <ServiceAccountIcon isActive={isActive} />,
  },  {
    TITLE: 'Settlements',
    LINK: 'settlements',
    SLUG: 'settlements',
    ISBUSINESS: true,
    ICON: (isActive: boolean) => <SettlementIcon isActive={isActive} />,
  }, 
  {
    TITLE: 'Reports',
    LINK: 'reports',
    SLUG: 'reports',
    ISBUSINESS: true,
    ICON: (isActive: boolean) => <ReportIcon isActive={isActive} />,
  },
  {
    TITLE: 'Preferences',
    LINK: 'preferences',
    SLUG: 'preferences',
    ISSETTINGS: true,
    ICON: (isActive: boolean) => <PreferenceIcon isActive={isActive} />,
  },  {
    TITLE: 'Fees and Pricing',
    LINK: 'pricing',
    SLUG: 'pricing',
    ISSETTINGS: true,
    ICON: (isActive: boolean) => <FeesPricingIcon isActive={isActive} />,
  },  {
    TITLE: 'Audit Logs',
    LINK: 'audit-logs',
    SLUG: 'audit-logs',
    ISSETTINGS: true,
    ICON: (isActive: boolean) => <AuditIcon isActive={isActive} />,
  },  
];

